logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9091/discovery-service/eureka
  instance:
    # Must has hostname or edge service may NPE
    hostname: localhost

spring:
  rabbitmq:
    host: 192.168.1.189
    username: pep_stomp
    password: 123456
    port: 5675
    virtual-host: /