logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9091/discovery-service/eureka
  instance:
    # Must has hostname or edge service may NPE
    hostname: localhost