---
spring:
  profiles: 16fd9588-252c-11e9-99b9-0242ac00011c
description: 普日项目
url:
  web: http://icmp/web
  api: http://icmp/api

---
spring:
  profiles: 7654321
description: 普日项目抢先版
url:
  web: http://localhost:8080/web
  api: http://localhost:8080/api