language: node_js
node_js: stable

install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "propersoft-ci"
  - git config user.email "hexin@propersoft.cn"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://$wwvonv@$GH_REF" dev:master

branches:
  only:
    - dev
env:
 global:
   - GH_REF: github.com/vonvww/oopstorm.github.io/tree/dev
